/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author vanessa-vaca1
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        __tabla = new javax.swing.JTable();
        search5 = new javax.swing.JButton();
        search1 = new javax.swing.JButton();
        search2 = new javax.swing.JButton();
        search3 = new javax.swing.JButton();
        search4 = new javax.swing.JButton();
        texto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        search6 = new javax.swing.JButton();
        search7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        UpPlaca = new javax.swing.JTextField();
        Up1 = new javax.swing.JButton();
        Up3 = new javax.swing.JButton();
        Up2 = new javax.swing.JButton();
        UpMarca = new javax.swing.JTextField();
        UpDir = new javax.swing.JTextField();
        UpNombre = new javax.swing.JTextField();
        UpCosto = new javax.swing.JTextField();
        UpFact = new javax.swing.JTextField();
        UpModel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        __tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(__tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 810, 150));

        search5.setText("Prima Mayor");
        jPanel1.add(search5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 130, 50));

        search1.setFont(new java.awt.Font("MathJax_Typewriter", 2, 12)); // NOI18N
        search1.setText("Mostrar Clientes");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        jPanel1.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 140, 50));

        search2.setText("Mostrar Facturas");
        search2.setActionCommand("allfact");
        search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search2ActionPerformed(evt);
            }
        });
        jPanel1.add(search2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 140, 50));

        search3.setText("Clientes y Vehiculos");
        search3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search3ActionPerformed(evt);
            }
        });
        jPanel1.add(search3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 140, 50));

        search4.setText("Vencimiento Polizas");
        jPanel1.add(search4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 140, 50));
        jPanel1.add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 190, -1));

        jLabel1.setText("Ingrese el nombre de Un cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, 50));

        search6.setText("Vehiculo");
        jPanel1.add(search6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        search7.setText("Poliza");
        search7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search7ActionPerformed(evt);
            }
        });
        jPanel1.add(search7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        jLabel2.setText("Actualizaciones");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 160, 30));
        jPanel1.add(UpPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 150, -1));

        Up1.setText("Actualizar direccion de cliente");
        jPanel1.add(Up1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        Up3.setText("Actualizar Marcoa y/o modelo de Vehiculo");
        jPanel1.add(Up3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, -1, -1));

        Up2.setText("Actualizar costo de una factura");
        jPanel1.add(Up2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, -1, -1));
        jPanel1.add(UpMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 150, -1));
        jPanel1.add(UpDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 150, -1));
        jPanel1.add(UpNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 150, -1));
        jPanel1.add(UpCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 150, -1));
        jPanel1.add(UpFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 150, -1));
        jPanel1.add(UpModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 150, 30));

        jLabel3.setText("Placas de Vehiculo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jLabel4.setText("Monto Nuevo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jLabel5.setText("Nombre de cliente");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel6.setText("Nueva Direccion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel7.setText("Marca de Vehiculo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, -1, -1));

        jLabel8.setText("Modelo De Vehiculo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, -1));

        jLabel9.setText("Placa de Vehiculo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search1ActionPerformed

    private void search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search2ActionPerformed

    private void search3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search3ActionPerformed

    private void search7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Up1;
    public javax.swing.JButton Up2;
    public javax.swing.JButton Up3;
    public javax.swing.JTextField UpCosto;
    public javax.swing.JTextField UpDir;
    public javax.swing.JTextField UpFact;
    public javax.swing.JTextField UpMarca;
    public javax.swing.JTextField UpModel;
    public javax.swing.JTextField UpNombre;
    public javax.swing.JTextField UpPlaca;
    public javax.swing.JTable __tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton search1;
    public javax.swing.JButton search2;
    public javax.swing.JButton search3;
    public javax.swing.JButton search4;
    public javax.swing.JButton search5;
    public javax.swing.JButton search6;
    public javax.swing.JButton search7;
    public javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
}
